package config

// Spanish for milk's text, keyed by the English that tr() is given next to
// the Portuguese. A string added to milk without a line here shows in English
// when bar.locale is "es".
@(rodata)
SPANISH := [][2]string{
	{"The operation failed", "La operación falló"},
	{"Out of range or switched off", "Fuera de alcance o apagado"},
	{"Authentication failed", "Falló la autenticación"},
	{"Device not found", "Dispositivo no encontrado"},
	{"Already in progress", "Operación ya en curso"},
	{"bluetoothctl (BlueZ) is not installed.", "bluetoothctl (BlueZ) no está instalado."},
	{"Loading…", "Cargando…"},
	{"No Bluetooth adapter found.", "No se encontró ningún adaptador Bluetooth."},
	{"Bluetooth is off.", "El Bluetooth está apagado."},
	{"Pairing…", "Emparejando…"},
	{"Trusting…", "Confiando…"},
	{"Connecting…", "Conectando…"},
	{"Disconnecting…", "Desconectando…"},
	{"Connected", "Conectado"},
	{"Click to pair", "Haz clic para emparejar"},
	{"Paired devices", "Dispositivos emparejados"},
	{"No paired devices.", "No hay dispositivos emparejados."},
	{"Other devices", "Otros dispositivos"},
	{"Searching…", "Buscando…"},
	{"Search for devices", "Buscar dispositivos"},
	{"Nothing playing", "Nada en reproducción"},
	{"Off", "Desactivadas"},
	{"Fast", "Rápidas"},
	{"Normal", "Normales"},
	{"Animations", "Animaciones"},
	{"Quick settings", "Ajustes rápidos"},
	{"Top", "Arriba"},
	{"Bottom", "Abajo"},
	{"Full", "Completa"},
	{"Floating", "Flotante"},
	{"Bar position", "Posición de la barra"},
	{"Bar style", "Estilo de la barra"},
	{"Bar height", "Altura de la barra"},
	{"Bar opacity", "Opacidad de la barra"},
	{"Gaps", "Espaciado (gaps)"},
	{"Window borders", "Bordes de las ventanas"},
	{"Master size", "Área principal"},
	{"Area toast", "Aviso de área"},
	{"All settings", "Toda la configuración"},
	{"Edit %s", "Editar %s"},
	{"Could not disconnect", "No se pudo desconectar"},
	{"Wrong or missing password", "Contraseña incorrecta o necesaria"},
	{"Timed out while connecting", "Se agotó el tiempo al conectar"},
	{"Network out of range", "Red fuera de alcance"},
	{"Could not connect", "No se pudo conectar"},
	{"NetworkManager (nmcli) is not installed.", "NetworkManager (nmcli) no está instalado."},
	{"Wired network", "Red cableada"},
	{"Wi-Fi is off.", "El Wi-Fi está apagado."},
	{"Available networks", "Redes disponibles"},
	{"Looking for networks…", "Buscando redes…"},
	{"No other networks found.", "No se encontraron otras redes."},
	{"Network settings", "Configuración de red"},
	{"Disconnect", "Desconectar"},
	{"Saved", "Guardada"},
	{"Connect", "Conectar"},
	{"Password", "Contraseña"},
	{"Clipboard", "Portapapeles"},
	{"Clear all", "Borrar todo"},
	{"Nothing copied yet", "Todavía no has copiado nada"},
	{"Text and pictures you copy", "Los textos e imágenes que copies"},
	{"show up here.", "aparecen aquí."},
	{"AREA", "ÁREA"},
	{"Apps", "Aplicaciones"},
	{"Run", "Ejecutar"},
	{"Windows", "Ventanas"},
	{"Search…", "Buscar…"},
	{"now", "ahora"},
	{"Notification", "Notificación"},
	{"unknown", "desconocido"},
	{"Another notification service is running (%s)", "Otro servicio de notificaciones está activo (%s)"},
	{"Notification service unavailable (no D-Bus)", "Servicio de notificaciones no disponible (sin D-Bus)"},
	{"Notifications", "Notificaciones"},
	{"No new notifications", "No hay notificaciones nuevas"},
	{"Do not disturb is on", "No molestar está activado"},
	{"Style", "Estilo"},
	{"Layouts", "Modelos"},
	{"Widgets", "Widgets"},
	{"Terminal", "Terminal"},
	{"Music", "Música"},
	{"START", "INICIO"},
	{"CENTER", "CENTRO"},
	{"END", "FINAL"},
	{"AVAILABLE", "DISPONIBLES"},
	{"Empty", "Vacío"},
	{"All on the bar", "Todos en la barra"},
	{"Pick a widget on the bar to move or remove it, or an available one to add it.", "Elige un widget de la barra para moverlo o quitarlo, o uno disponible para añadirlo."},
	{"Add %s to:", "Añadir %s a:"},
	{"Start", "Inicio"},
	{"Center", "Centro"},
	{"End", "Final"},
	{"Remove", "Quitar"},
	{"BAR WIDGETS", "WIDGETS DE LA BARRA"},
	{"Visual effects", "Efectos visuales"},
	{"Shadows, animations, transparency, blur and smooth corners", "Sombras, animaciones, transparencia, desenfoque y esquinas suaves"},
	{"Compositor", "Compositor"},
	{"lactase is not installed", "lactase no está instalado"},
	{"lactase running", "lactase activo"},
	{"lactase running (OpenGL)", "lactase activo (OpenGL)"},
	{"lactase running (XRender)", "lactase activo (XRender)"},
	{"Another compositor is running", "Otro compositor está activo"},
	{"Stopped", "Detenido"},
	{"lactase settings", "Configuración de lactase"},
	{"Shadows, animations, transparency, blur and per-application rules live in lactase's settings.", "Las sombras, animaciones, transparencia, desenfoque y reglas por aplicación están en la configuración de lactase."},
	{"Window corners follow the radius under Windows; with lactase they are smooth.", "Las esquinas de las ventanas siguen el radio de Ventanas; con lactase quedan suavizadas."},
	{"Install lactase with milk's installer (./install.sh) for shadows, animations and transparency.", "Instala lactase con el instalador de milk (./install.sh) para tener sombras, animaciones y transparencia."},
	{"Default", "Predeterminado"},
	{"Automatic", "Automático"},
	{"Welcome to milk", "Bienvenido a milk"},
	{"Let's make your desktop yours in five quick steps.", "Vamos a dejar tu escritorio a tu gusto en cinco pasos rápidos."},
	{"Theme", "Tema"},
	{"Light or dark", "Claro u oscuro"},
	{"Keyboard", "Teclado"},
	{"Layout and variant", "Distribución y variante"},
	{"Wallpapers", "Fondos de pantalla"},
	{"One for all or one per area", "Uno para todas o uno por área"},
	{"Bar", "Barra"},
	{"Position and style", "Posición y estilo"},
	{"Light", "Claro"},
	{"Dark", "Oscuro"},
	{"Dark variant", "Variante oscura"},
	{"Light variant", "Variante clara"},
	{"No dead keys: ´ ~ ^ do not accent the next letter", "Sin teclas muertas: ´ ~ ^ no acentúan la letra siguiente"},
	{"No dead keys: ´ ~ ^ never accent", "Sin teclas muertas: ´ ~ ^ no acentúan"},
	{"Search layouts…", "Buscar distribución…"},
	{"No layout found", "No se encontró ninguna distribución"},
	{"VARIANT", "VARIANTE"},
	{"Type here to test: symbols, accents, @, / …", "Escribe aquí para probar: ñ, acentos, @, / …"},
	{"None (bar colour)", "Ninguno (color de la barra)"},
	{"Same on all", "El mismo en todas"},
	{"One per area", "Uno por área"},
	{"Loading wallpapers…", "Cargando fondos de pantalla…"},
	{"Loading wallpapers… %d of %d", "Cargando fondos de pantalla… %d de %d"},
	{"%d pictures found", "%d imágenes encontradas"},
	{"No wallpaper", "Sin fondo de pantalla"},
	{"solid bar colour", "color sólido de la barra"},
	{"Edge to edge", "De borde a borde"},
	{"Floating top", "Arriba flotante"},
	{"Margins and rounded corners", "Márgenes y esquinas redondeadas"},
	{"Floating bottom", "Abajo flotante"},
	{"One per area · %d areas", "Uno por área · %d áreas"},
	{"None (solid bar colour)", "Ninguno (color sólido de la barra)"},
	{"%s · every area", "%s · todas las áreas"},
	{"floating", "flotante"},
	{"edge to edge", "de borde a borde"},
	{"THEME", "TEMA"},
	{"KEYBOARD", "TECLADO"},
	{"WALLPAPERS", "FONDOS DE PANTALLA"},
	{"BAR", "BARRA"},
	{"Change", "Cambiar"},
	{"milk settings", "Configuración de milk"},
	{"Appearance", "Apariencia"},
	{"Colour theme, profile picture and animations.", "Tema de colores, foto de perfil y animaciones."},
	{"One image for every area or one per area.", "Una imagen para todas las áreas o una para cada área."},
	{"Position, style, size, widgets and date/time formats.", "Posición, estilo, tamaño, widgets y formatos de fecha y hora."},
	{"Effects", "Efectos"},
	{"Shadows, animations and transparency with lactase, milk's compositor.", "Sombras, animaciones y transparencia con lactase, el compositor de milk."},
	{"Gaps, borders and animations. Border colours follow the theme.", "Espaciado, bordes y animaciones. Los colores de los bordes siguen el tema."},
	{"Shortcuts", "Atajos"},
	{"Key combinations that open applications, commands and sites.", "Combinaciones de teclas que abren aplicaciones, comandos y sitios."},
	{"Language and keyboard", "Idioma y teclado"},
	{"milk's language and the keyboard layout and variant, applied at once.", "Idioma de milk y distribución y variante del teclado, aplicados al instante."},
	{"Pop-ups shown in a corner of the screen.", "Avisos que aparecen en una esquina de la pantalla."},
	{"History of copied text and images.", "Historial de textos e imágenes copiados."},
	{"Areas", "Áreas"},
	{"Area names and icons, shown by the area toast and on the bar.", "Nombres e iconos de las áreas, en el aviso de área y en la barra."},
	{"AREA TOAST AND BAR", "AVISO DE ÁREA Y BARRA"},
	{"Show “%s” before the name", "Mostrar “%s” antes del nombre"},
	{"AREA N", "ÁREA N"},
	{"In the toast when the area changes. An area without a name always shows its number.", "En el aviso al cambiar de área. Un área sin nombre siempre muestra su número."},
	{"Icons on the bar", "Iconos en la barra"},
	{"Areas with an icon show it instead of their dot", "Las áreas con icono lo muestran en lugar del punto"},
	{"Icon of area %d", "Icono del área %d"},
	{"About", "Acerca de"},
	{"Version, files and the setup wizard.", "Versión, archivos y asistente inicial."},
	{"Animation speed", "Velocidad de las animaciones"},
	{"Windows, bar, panels and toasts", "Ventanas, barra, paneles y avisos"},
	{"Slow", "Lentas"},
	{"Language", "Idioma"},
	{"Menus, panels, dates and this app", "Menús, paneles, fechas y esta aplicación"},
	{"Settings", "Configuración"},
	{"Height", "Altura"},
	{"Opacity", "Opacidad"},
	{"Margin (floating)", "Margen (flotante)"},
	{"Corners (floating)", "Esquinas (flotante)"},
	{"Date", "Fecha"},
	{"Clock", "Reloj"},
	{"Between windows and the screen edges", "Entre las ventanas y los bordes de la pantalla"},
	{"Focused window: the theme accent", "Ventana enfocada: el color de acento del tema"},
	{"Rounded corners", "Esquinas redondeadas"},
	{"Radius of the window corners", "Radio de las esquinas de las ventanas"},
	{"Master area", "Área principal"},
	{"Width of the main window", "Ancho de la ventana principal"},
	{"Focus follows mouse", "El foco sigue al ratón"},
	{"Focus the window under the pointer", "Enfocar la ventana bajo el puntero"},
	{"Window animation", "Animación de las ventanas"},
	{"Duration when opening, moving and resizing", "Duración al abrir, mover y redimensionar"},
	{"Receive pop-ups from applications", "Recibir avisos de las aplicaciones"},
	{"Do not disturb", "No molestar"},
	{"Keep them in the history without showing them", "Guardarlos en el historial sin mostrarlos"},
	{"Time on screen", "Tiempo en pantalla"},
	{"When the application does not say", "Cuando la aplicación no lo indica"},
	{"Position", "Posición"},
	{"Top right", "Arriba a la derecha"},
	{"Bottom right", "Abajo a la derecha"},
	{"History", "Historial"},
	{"Keep what is copied", "Guardar lo que se copie"},
	{"Items kept", "Elementos guardados"},
	{"Keep after restarting", "Conservar al reiniciar"},
	{"Save the history in milk's folder", "Guardar el historial en la carpeta de milk"},
	{"Area %d", "Área %d"},
	{"Version %s", "Versión %s"},
	{"CONFIGURATION", "CONFIGURACIÓN"},
	{"DATA", "DATOS"},
	{"Run the setup wizard again", "Volver a ejecutar el asistente inicial"},
	{"Open milk.json", "Abrir milk.json"},
	{"The wizard appears the next time milk starts.", "El asistente aparecerá la próxima vez que se inicie milk."},
	{"The wizard will open next time", "El asistente se abrirá la próxima vez"},
	{"Could not save", "No se pudo guardar"},
	{"Saved and applied", "Guardado y aplicado"},
	{"Space", "Espacio"},
	{"Mute", "Silencio"},
	{"Brightness +", "Brillo +"},
	{"Brightness −", "Brillo −"},
	{"Next", "Siguiente"},
	{"Previous", "Anterior"},
	{"Your shortcuts", "Tus atajos"},
	{"Add shortcut", "Añadir atajo"},
	{"No shortcuts yet: add one to open your favourite apps and sites.", "Todavía no hay atajos: crea uno para abrir tus aplicaciones y sitios favoritos."},
	{"milk's shortcuts", "Atajos de milk"},
	{"New shortcut", "Nuevo atajo"},
	{"Edit shortcut", "Editar atajo"},
	{"KEY COMBINATION", "COMBINACIÓN DE TECLAS"},
	{"Press the combination…  (Esc cancels)", "Pulsa la combinación…  (Esc cancela)"},
	{"Click to change", "Haz clic para cambiar"},
	{"Click here and press the key combination", "Haz clic aquí y pulsa la combinación de teclas"},
	{"Already one of your shortcuts: it is replaced when you save.", "Ya es uno de tus atajos: se sustituirá al guardar."},
	{"Replaces: %s (milk shortcut)", "Sustituye: %s (atajo de milk)"},
	{"OPEN", "ABRIR"},
	{"Application", "Aplicación"},
	{"Command", "Comando"},
	{"Site or folder", "Sitio o carpeta"},
	{"Search applications…", "Buscar aplicación…"},
	{"E.g. alacritty -e htop", "Ej.: alacritty -e htop"},
	{"Run with /bin/sh -c, like milk's other shortcuts.", "Se ejecuta con /bin/sh -c, como los demás atajos de milk."},
	{"E.g. https://example.com or ~/Documents", "Ej.: https://example.com o ~/Documentos"},
	{"Opened with xdg-open in the default application.", "Se abre con xdg-open en la aplicación predeterminada."},
	{"Save", "Guardar"},
	{"Cancel", "Cancelar"},
	{"No application found", "No se encontró ninguna aplicación"},
	{"Bar background", "Fondo de la barra"},
	{"Surface", "Superficie"},
	{"Foreground", "Texto"},
	{"Muted", "Texto suave"},
	{"Accent", "Acento"},
	{"Accent foreground", "Texto sobre el acento"},
	{"Warning", "Alerta"},
	{"Window border", "Borde de las ventanas"},
	{"Focused window", "Ventana enfocada"},
	{"YOUR THEMES", "TUS TEMAS"},
	{"New theme", "Nuevo tema"},
	{"Make a theme with your own colours: it applies to the bar, windows, panels and terminal.", "Crea un tema con tus colores: se aplica a la barra, las ventanas, los paneles y la terminal."},
	{"My theme", "Mi tema"},
	{"Give the theme a name.", "Ponle un nombre al tema."},
	{"That is the name of a milk theme.", "Ese nombre es de un tema de milk."},
	{"There is already a theme with that name.", "Ya existe un tema con ese nombre."},
	{"Edit theme", "Editar tema"},
	{"Theme name", "Nombre del tema"},
	{"Hue", "Tono"},
	{"Saturation", "Saturación"},
	{"Lightness", "Luminosidad"},
	{"Save and use", "Guardar y usar"},
	{"Confirm delete", "Confirmar eliminación"},
	{"Delete", "Eliminar"},
	{"Skip setup", "Omitir configuración"},
	{"Let's go", "Empezar"},
	{"Back", "Atrás"},
	{"Choose your theme", "Elige tu tema"},
	{"Colours for the bar, the panels, window borders and the terminal.", "Colores de la barra, los paneles, los bordes de las ventanas y la terminal."},
	{"Pick your keyboard layout and variant, then try it in the test field.", "Elige la distribución y la variante de tu teclado y pruébalas escribiendo en el campo de prueba."},
	{"One image for every workspace, or a different one for each area.", "Una imagen para todas las áreas de trabajo, o una distinta para cada área."},
	{"Where the bar sits and how it meets the screen edges.", "Dónde va la barra y cómo se apoya en la pantalla."},
	{"All set", "Todo listo"},
	{"Review your choices. Everything can be changed later in the bar's quick settings or in milk.json.", "Revisa tus elecciones. Todo se puede cambiar después en los ajustes rápidos de la barra o en milk.json."},
	{"Launcher", "Lanzador"},
	{"Active window", "Ventana activa"},
	{"Workspaces", "Áreas"},
	{"Open windows", "Ventanas abiertas"},
	{"System tray", "Bandeja del sistema"}, // milk tray
	{"Window", "Ventana"},
	{"Media", "Multimedia"},
	{"Network", "Red"},
	{"Bluetooth", "Bluetooth"},
	{"Volume", "Volumen"},
	{"Brightness", "Brillo"},
	{"Battery", "Batería"},
	{"Session", "Sesión"},
	{"Spacer", "Espacio"},
	{"milk", "milk"},
	{"The default: open windows left, areas centred", "El predeterminado: ventanas abiertas a la izquierda, áreas en el centro"},
	{"Minimal", "Mínimo"},
	{"Just areas, the clock and the essentials", "Solo áreas, reloj y lo esencial"},
	{"Classic", "Clásico"},
	{"Windows-like: bottom, clock in the corner", "Como en Windows: abajo, con el reloj en la esquina"},
	{"Centred", "Centrado"},
	{"Floating at the bottom, essentials in the middle", "Flotante abajo, con lo esencial en el centro"},
	{"macOS", "macOS"},
	{"At the top, clock and settings on the right", "Arriba, con reloj y ajustes a la derecha"},
	{"Open the terminal", "Abrir la terminal"},
	{"Open the application launcher", "Abrir el lanzador de aplicaciones"},
	{"Close the window", "Cerrar la ventana"},
	{"Swap with the master window", "Intercambiar con la ventana principal"},
	{"Previous layout", "Disposición anterior"},
	{"Toggle floating", "Alternar ventana flotante"},
	{"Fullscreen", "Pantalla completa"},
	{"Go to area 1…9", "Ir al área 1…9"},
	{"Move the window to area 1…9", "Mover la ventana al área 1…9"},
	{"Also show area 1…9", "Mostrar también el área 1…9"},
	{"Also put the window on area 1…9", "Poner la ventana también en el área 1…9"},
	{"Previous area", "Área anterior"},
	{"Clipboard history", "Historial del portapapeles"},
	{"Notification panel", "Panel de notificaciones"},
	{"Screenshot of a region", "Captura de una región de la pantalla"},
	{"Reload milk.json", "Recargar milk.json"},
	{"Quit milk", "Salir de milk"},
	// milk's own shortcuts (config.DEFAULT_KEYS) and their editor.
	{"Open the file manager", "Abrir el gestor de archivos"},
	{"Switch between windows, backwards", "Alternar entre las ventanas, hacia atrás"},
	{"Focus the next window", "Enfocar la ventana siguiente"},
	{"Focus the previous window", "Enfocar la ventana anterior"},
	{"Shrink the master area", "Reducir el área principal"},
	{"Grow the master area", "Ampliar el área principal"},
	{"More windows in the master area", "Más ventanas en el área principal"},
	{"Fewer windows in the master area", "Menos ventanas en el área principal"},
	{"Tile layout", "Disposición en mosaico"},
	{"Floating layout", "Disposición flotante"},
	{"Monocle layout", "Disposición monóculo"},
	{"Show every area", "Ver todas las áreas"},
	{"Put the window on every area", "Poner la ventana en todas las áreas"},
	{"Back to the last area", "Volver a la última área"},
	{"Focus the previous monitor", "Enfocar el monitor anterior"},
	{"Focus the next monitor", "Enfocar el monitor siguiente"},
	{"Move the window to the previous monitor", "Mover la ventana al monitor anterior"},
	{"Move the window to the next monitor", "Mover la ventana al monitor siguiente"},
	{"a shortcut of yours", "un atajo tuyo"},
	{"Hold the modifiers and press a number (1…9).", "Mantén las teclas modificadoras y pulsa un número (1…9)."},
	{"milk's shortcuts restored", "Atajos de milk restaurados"},
	{"Restore all", "Restaurar todos"},
	{"Click a shortcut to change its keys", "Haz clic en un atajo para cambiar sus teclas"},
	{"APPS AND PANELS", "APLICACIONES Y PANELES"},
	{"TILING LAYOUT", "DISPOSICIÓN EN MOSAICO"},
	{"AREAS AND MONITORS", "ÁREAS Y MONITORES"},
	{"SYSTEM", "SISTEMA"},
	{"milk shortcut", "Atajo de milk"},
	{"milk shortcut, in the tiling mode only", "Atajo de milk, solo en el modo mosaico"},
	{"milk shortcut, in the floating mode only", "Atajo de milk, solo en el modo flotante"},
	{"KEYS", "TECLAS"},
	{"Replaces: %s", "Reemplaza: %s"},
	{"Also on: %s", "También en: %s"},
	{"No keys: this shortcut is off.", "Sin teclas: este atajo queda desactivado."},
	{"Press the modifiers with a number…  (Esc cancels)", "Pulsa las teclas modificadoras con un número…  (Esc cancela)"},
	{"Add a key combination", "Añadir una combinación de teclas"},
	{"An area shortcut works with the numbers 1 to 9: Super+Ctrl with 3 becomes Super+Ctrl+1…9.", "Un atajo de área vale para los números del 1 al 9: Super+Ctrl con 3 se convierte en Super+Ctrl+1…9."},
	{"Restore the default", "Restaurar el predeterminado"},
	{"Use a modifier with that key. On their own: Super, F1…F12, Print Screen, Pause, Menu and media keys.", "Usa un modificador con esa tecla. Solas: Super, F1…F12, Impr Pant, Pausa, Menú y multimedia."},
	{"Super on its own acts when the key is released, if no other key was used with it.", "Super solo actúa al soltar la tecla, si no se usó ninguna otra con ella."},
	// Floating mode, window menus, desktop icons settings.
	{"Files", "Archivos"},
	{"Applications…", "Aplicaciones…"},
	{"New folder", "Nueva carpeta"},
	{"Arrange icons", "Ordenar los iconos"},
	{"Open the Desktop folder", "Abrir la carpeta del escritorio"},
	{"Wallpaper…", "Fondo de pantalla…"},
	{"Reload", "Recargar"},
	{"Log out", "Cerrar sesión"},
	{"No windows", "No hay ventanas"},
	{"Minimize", "Minimizar"},
	{"Restore", "Restaurar"},
	{"Maximize", "Maximizar"},
	{"Shade", "Enrollar"},
	{"Always on top", "Siempre encima"},
	{"Always below", "Siempre debajo"},
	{"On every area", "En todas las áreas"},
	{"Title bar", "Barra de título"},
	{"Left half", "Mitad izquierda"},
	{"Right half", "Mitad derecha"},
	{"Centre", "Centrar"},
	{"Move to area", "Mover al área"},
	{"Move to the other monitor", "Mover al otro monitor"},
	{"Close", "Cerrar"},
	{"minimized", "minimizada"},
	{"Mode", "Modo"},
	{"Windows with title bars that you move and overlap", "Ventanas con barra de título que mueves y superpones"},
	{"Windows share the screen between them", "Las ventanas se reparten la pantalla"},
	{"Tiling", "En mosaico"},
	{"General", "General"},
	{"Behaviour", "Comportamiento"},
	{"Margin", "Margen"},
	{"Around maximized and snapped windows", "Alrededor de las ventanas maximizadas y ajustadas"},
	{"Buttons", "Botones"},
	{"Icons", "Iconos"},
	{"Circles", "Círculos"},
	{"Button side", "Lado de los botones"},
	{"Right", "Derecha"},
	{"Left", "Izquierda"},
	{"Title", "Título"},
	{"Document — Editor", "Documento — Editor"},
	{"New windows", "Ventanas nuevas"},
	{"Where windows appear", "Dónde aparecen las ventanas"},
	{"Free space", "Espacio libre"},
	{"Pointer", "Puntero"},
	{"Cascade", "Cascada"},
	{"Snap to edges", "Ajustar a los bordes"},
	{"Drag to an edge: half, quarter or maximized", "Arrastra a un borde: mitad, cuarto o maximizada"},
	{"Resistance", "Resistencia"},
	{"Windows stick to the edges and to each other", "Las ventanas se pegan a los bordes y entre sí"},
	{"Raise on focus", "Traer al frente al enfocar"},
	{"With focus following the mouse", "Con el foco siguiendo al ratón"},
	{"Files on the desktop", "Archivos en el escritorio"},
	{"What the Desktop folder holds, as icons", "Lo que contiene la carpeta Escritorio, como iconos"},
	{"Area shortcuts", "Atajos de las áreas"},
	{"The shortcuts of each area", "Los atajos de cada área"},
	{"In the folder", "En la carpeta"},
	{"Hidden", "Ocultos"},
	{"Icon size", "Tamaño de los iconos"},
	{"Open with one click", "Abrir con un clic"},
	{"Image thumbnails", "Miniaturas de imágenes"},
	{"Hidden files", "Archivos ocultos"},
	{"Arrange by", "Ordenar por"},
	{"For icons without a place yet", "Para los iconos que aún no tienen lugar"},
	{"Name", "Nombre"},
	{"Type", "Tipo"},
	{"Windows share the screen without overlapping", "Las ventanas se reparten la pantalla sin superponerse"},
	{"Title bars, dragging, maximizing and snapping", "Barras de título, arrastrar, maximizar y ajustar"},
	{"Show the Desktop folder as icons over the wallpaper", "Mostrar la carpeta Escritorio como iconos sobre el fondo"},
	{"Side by side like dwm, or floating with title bars like openbox and Windows.", "Lado a lado como en dwm, o flotantes con barra de título como en openbox y Windows."},
	{"Tiling or floating", "En mosaico o flotantes"},
	{"WINDOWS", "VENTANAS"},
	{"files on the desktop", "archivos en el escritorio"},
	{"Tiling or floating, borders, title bars and animations.", "En mosaico o flotantes, bordes, barras de título y animaciones."},
	{"Desktop", "Escritorio"},
	{"File and shortcut icons over the wallpaper.", "Iconos de archivos y atajos sobre el fondo de pantalla."},
	{"Switch between windows", "Cambiar entre ventanas"},
	{"Maximize / restore", "Maximizar / restaurar"},
	{"Restore or minimize", "Restaurar o minimizar"},
	{"Centre the window", "Centrar la ventana"},
	{"Show the desktop", "Mostrar el escritorio"},
	{"Window menu", "Menú de la ventana"},
	{"Window action", "Acción de la ventana"},
	{"WHAT IT DOES", "QUÉ HACE"},
	{"Key combinations for applications, commands, sites and window actions.", "Combinaciones de teclas para aplicaciones, comandos, sitios y acciones de las ventanas."},
	{"Snap to the left half", "Ajustar a la mitad izquierda"},
	{"Snap to the right half", "Ajustar a la mitad derecha"},
	{"Snap to the top-left quarter", "Ajustar al cuarto superior izquierdo"},
	{"Snap to the top-right quarter", "Ajustar al cuarto superior derecho"},
	{"Snap to the bottom-left quarter", "Ajustar al cuarto inferior izquierdo"},
	{"Snap to the bottom-right quarter", "Ajustar al cuarto inferior derecho"},
	{"Show / hide the title bar", "Mostrar / ocultar la barra de título"},
	{"Send to the back", "Enviar al fondo"},
	{"Desktop menu", "Menú del escritorio"},
	{"Window list", "Lista de ventanas"},
	{"Next area", "Área siguiente"},
	{"Take the window to the next area", "Llevar la ventana al área siguiente"},
	{"Take the window to the previous area", "Llevar la ventana al área anterior"},
	{"Open", "Abrir"},
	{"Open in terminal", "Abrir en la terminal"},
	{"Copy path", "Copiar ruta"},
	{"Copy paths", "Copiar rutas"},
	{"Rename…", "Cambiar nombre…"},
	{"Move to Trash", "Mover a la papelera"},
	// Settings → About: milk update.
	{"Update milk…", "Actualizar milk…"},
	{"Downloads and builds milk, Spoil and lactase, then restarts milk without closing your windows.",
	 "Descarga y compila milk, Spoil y lactase y reinicia milk sin cerrar tus ventanas."},
	{"Press Enter to close.", "Pulsa Enter para cerrar."},
	{"Could not open the terminal", "No se pudo abrir el terminal"},
	// Settings → Appearance: tabs and the profile picture.
	{"Theme", "Tema"},
	{"General", "General"},
	{"Profile picture", "Foto de perfil"},
	{"On the lock screen and the login screens", "En la pantalla de bloqueo y en las de inicio de sesión"},
	{"Choose…", "Elegir…"},
	{"Remove", "Quitar"},
	{"Back", "Volver"},
	{"Choose a profile picture", "Elige una foto de perfil"},
	{"Pictures from your Pictures folder, the wallpapers and the system", "Imágenes de tu carpeta Imágenes, de los fondos y del sistema"},
	{"No pictures found", "No se encontraron imágenes"},
	{"Could not open the picture", "No se pudo abrir la imagen"},
	{"Could not save the picture", "No se pudo guardar la foto"},
	{"Profile picture saved", "Foto de perfil guardada"},
	{"Profile picture removed", "Foto de perfil quitada"},
	// Desktop icons kept to some areas.
	{"Show on", "Mostrar en"},
	{"Area", "Área"},
	{"Every area", "Todas las áreas"},
	{"current", "actual"},
	{"New files appear on", "Los archivos nuevos aparecen en"},
	{"Per icon: right-click → Show on", "Por icono: clic derecho → Mostrar en"},
	{"Current area only", "Solo en el área actual"},
	// The wallpaper theme (matugen).
	{"Wallpaper", "Fondo de pantalla"},
	{"Colours of the wallpaper", "Colores del fondo de pantalla"},
	{"Install matugen", "Instala matugen"},
	{"Colour style", "Estilo de color"},
	{"Tonal", "Tonal"},
	{"Content", "Contenido"},
	{"Expressive", "Expresivo"},
	{"Faithful", "Fiel"},
	{"Fruit salad", "Ensalada de frutas"},
	{"Monochrome", "Monocromo"},
	{"Neutral", "Neutro"},
	{"Rainbow", "Arcoíris"},
	{"Vibrant", "Vibrante"},
	// Night light, the volume/brightness pop-up (Settings → Display, quick settings, shortcuts).
	{"Night light", "Luz nocturna"},
	{"Always", "Siempre"},
	{"Display", "Pantalla"},
	{"Night light and the volume and brightness pop-up.", "Luz nocturna y el aviso de volumen y brillo."},
	{"Warmer colours at night, easier on the eyes", "Colores más cálidos de noche, más agradables para la vista"},
	{"All the time", "Todo el tiempo"},
	{"No place set: using the hours below", "Sin lugar definido: se usa el horario de abajo"},
	{"Tonight: %s to %s", "Esta noche: de %s a %s"},
	{"The sun does not set or rise these days", "El sol no se pone o no sale estos días"},
	{"When", "Cuándo"},
	{"Sunset", "Atardecer"},
	{"Hours", "Horario"},
	{"Temperature", "Temperatura"},
	{"Drag to see it on screen", "Arrastra para verla en la pantalla"},
	{"to", "a"},
	{"Place", "Lugar"},
	{"Degrees; south and west are negative", "Grados; el sur y el oeste son negativos"},
	{"The time zone gives no place", "La zona horaria no indica un lugar"},
	{"Time zone", "Zona horaria"},
	{"Latitude", "Latitud"},
	{"Longitude", "Longitud"},
	{"Transition", "Transición"},
	{"How long the change takes", "Cuánto tarda el cambio"},
	{"Instant", "Inmediata"},
	{"Volume and brightness pop-up", "Aviso de volumen y brillo"},
	{"When the volume and brightness keys are used", "Al usar las teclas de volumen y brillo"},
	{"Disabled", "Desactivado"},
	{"Middle", "Centro"},
	{"Night light on / off", "Activar / desactivar la luz nocturna"},
	{"Volume up", "Subir el volumen"},
	{"Volume down", "Bajar el volumen"},
	{"Brightness up", "Subir el brillo"},
	{"Brightness down", "Bajar el brillo"},
	// GTK and Qt apps in milk's colours (appearance.themeApps).
	{"Colour GTK and Qt apps", "Colorear apps GTK y Qt"},
	{"Other apps use the theme's colours too", "Las demás apps también usan los colores del tema"},
	// The lock screen, idle handling and the session menu (package lock).
	{"Lock", "Bloquear"},
	{"Lock the screen", "Bloquear la pantalla"},
	{"Suspend", "Suspender"},
	{"Restart", "Reiniciar"},
	{"Power off", "Apagar"},
	{"Caps Lock is on", "Bloq Mayús está activado"},
	{"Checking…", "Verificando…"},
	{"Wrong password", "Contraseña incorrecta"},
	{"Type your password to unlock", "Escribe tu contraseña para desbloquear"},
	{"Lock & idle", "Bloqueo e inactividad"},
	{"The lock screen and what happens when the computer is not in use.", "La pantalla de bloqueo y lo que pasa cuando no se usa el equipo."},
	{"Lock automatically", "Bloquear automáticamente"},
	{"Ask for the password after a while without use", "Pedir la contraseña tras un tiempo sin uso"},
	{"Lock after", "Bloquear tras"},
	{"Without keyboard or mouse input", "Sin usar el teclado ni el ratón"},
	{"Dim the screen after", "Atenuar la pantalla tras"},
	{"A warning before locking or turning off", "Un aviso antes de bloquear o apagar"},
	{"Turn the screen off after", "Apagar la pantalla tras"},
	{"Suspend after", "Suspender tras"},
	{"The computer goes to sleep", "El equipo entra en reposo"},
	{"Lock when suspending", "Bloquear al suspender"},
	{"Also when hibernating", "También al hibernar"},
	{"Stay awake in fullscreen", "Mantener activa en pantalla completa"},
	{"A fullscreen window counts as use", "Una ventana en pantalla completa cuenta como uso"},
	{"Never", "Nunca"},
	{"Lock now", "Bloquear ahora"},
	{"Video players and browsers hold idle off while they play.", "Los reproductores de vídeo y los navegadores aplazan la inactividad mientras reproducen."},
	{"Shortcut: %s. %s", "Atajo: %s. %s"},
	// The polkit password dialog (package polkit).
	{"Authentication required", "Autenticación necesaria"},
	{"A program needs administrator rights.", "Un programa necesita permisos de administrador."},
	{"As %s", "Como %s"},
	{"switch", "cambiar"},
	{"Waiting for polkit…", "Esperando a polkit…"},
	{"Authenticate", "Autenticar"},
	{"Could not reach polkit's password checker.", "No se pudo contactar con el verificador de contraseñas de polkit."},
	{"Wrong password. Try again.", "Contraseña incorrecta. Inténtalo de nuevo."},
	// Audio devices in the volume card (bar/audio.odin).
	{"Output", "Salida"},
	{"Input", "Entrada"},
	{"Could not switch", "No se pudo cambiar"},
	// Settings → Bar → Scripts: widgets made by a command (oobe/barscripts.odin).
	{"Scripts", "Scripts"},
	{"Widgets made by a command", "Widgets hechos con un comando"},
	{"What the command prints shows on the bar, like polybar's scripts.", "Lo que el comando escribe aparece en la barra, como los scripts de polybar."},
	{"New widget", "Nuevo widget"},
	{"Edit widget", "Editar widget"},
	{"My widget", "Mi widget"},
	{"Widget name", "Nombre del widget"},
	{"No widgets yet: make one or start from an example.", "Aún no hay widgets: crea uno o empieza por un ejemplo."},
	{"Always running", "Siempre activo"},
	{"Every %s", "Cada %s"},
	{"Not on the bar", "Fuera de la barra"},
	{"EXAMPLES", "EJEMPLOS"},
	{"CPU", "Procesador"},
	{"Memory", "Memoria"},
	{"Free disk", "Disco libre"},
	{"Weather", "Clima"},
	{"COMMAND", "COMANDO"},
	{"E.g. date +%H:%M", "Ej.: date +%H:%M"},
	{"Test", "Probar"},
	{"Running…", "Ejecutando…"},
	{"On the bar: %s", "En la barra: %s"},
	{"Runs the command once and shows what the bar would show.", "Ejecuta el comando una vez y muestra lo que aparecería en la barra."},
	{"UPDATES", "ACTUALIZACIÓN"},
	{"On an interval", "Cada cierto tiempo"},
	{"Interval", "Intervalo"},
	{"The first line the command prints shows; it runs again after the interval.", "Aparece la primera línea que escribe el comando; se ejecuta de nuevo tras el intervalo."},
	{"The command keeps running, and every line it prints updates the widget.", "El comando sigue ejecutándose, y cada línea que escribe actualiza el widget."},
	{"ON CLICK (OPTIONAL)", "AL HACER CLIC (OPCIONAL)"},
	{"Icon of %s", "Icono de %s"},
	{"Widget icon", "Icono del widget"},
	{"Or the name of a Tabler icon (tabler.io/icons)", "O el nombre de un icono de Tabler (tabler.io/icons)"},
	{"Give the widget a name (up to 40 letters).", "Ponle un nombre al widget (hasta 40 letras)."},
	{"Write the command whose output shows on the bar.", "Escribe el comando cuya salida aparece en la barra."},
	{"There is already a widget with that name.", "Ya hay un widget con ese nombre."},
	{"Write the command first.", "Escribe el comando primero."},
	{"Could not run the command.", "No se pudo ejecutar el comando."},
	{"Failed (code %d): %s", "Falló (código %d): %s"},
	{"Failed (code %d), with no output.", "Falló (código %d), sin salida."},
	{"Nothing within %d s: the command was still running.", "Nada en %d s: el comando seguía ejecutándose."},
	{"It printed nothing: the widget stays hidden.", "No escribió nada: el widget queda oculto."},
}
