package config

// Spanish for milk's text, keyed by the English that tr() is given next to
// the Portuguese. A string added to milk without a line here shows in English
// when bar.locale is "es".
@(rodata)
SPANISH := [][2]string{
	{"The operation failed", "La operación falló"},
	{"Out of range or switched off", "Fuera de alcance o apagado"},
	{"Authentication failed", "Falló la autenticación"},
	{"Device not found", "Dispositivo no encontrado"},
	{"Already in progress", "Operación ya en curso"},
	{"bluetoothctl (BlueZ) is not installed.", "bluetoothctl (BlueZ) no está instalado."},
	{"Loading…", "Cargando…"},
	{"No Bluetooth adapter found.", "No se encontró ningún adaptador Bluetooth."},
	{"Bluetooth is off.", "El Bluetooth está apagado."},
	{"Pairing…", "Emparejando…"},
	{"Trusting…", "Confiando…"},
	{"Connecting…", "Conectando…"},
	{"Disconnecting…", "Desconectando…"},
	{"Connected", "Conectado"},
	{"Click to pair", "Haz clic para emparejar"},
	{"Paired devices", "Dispositivos emparejados"},
	{"No paired devices.", "No hay dispositivos emparejados."},
	{"Other devices", "Otros dispositivos"},
	{"Searching…", "Buscando…"},
	{"Search for devices", "Buscar dispositivos"},
	{"Nothing playing", "Nada en reproducción"},
	{"Off", "Desactivadas"},
	{"Fast", "Rápidas"},
	{"Normal", "Normales"},
	{"Animations", "Animaciones"},
	{"Quick settings", "Ajustes rápidos"},
	{"Top", "Arriba"},
	{"Bottom", "Abajo"},
	{"Full", "Completa"},
	{"Floating", "Flotante"},
	{"Bar position", "Posición de la barra"},
	{"Bar style", "Estilo de la barra"},
	{"Bar height", "Altura de la barra"},
	{"Bar opacity", "Opacidad de la barra"},
	{"Gaps", "Espaciado (gaps)"},
	{"Window borders", "Bordes de las ventanas"},
	{"Master size", "Área principal"},
	{"Area toast", "Aviso de área"},
	{"All settings", "Toda la configuración"},
	{"Edit %s", "Editar %s"},
	{"Could not disconnect", "No se pudo desconectar"},
	{"Wrong or missing password", "Contraseña incorrecta o necesaria"},
	{"Timed out while connecting", "Se agotó el tiempo al conectar"},
	{"Network out of range", "Red fuera de alcance"},
	{"Could not connect", "No se pudo conectar"},
	{"NetworkManager (nmcli) is not installed.", "NetworkManager (nmcli) no está instalado."},
	{"Wired network", "Red cableada"},
	{"Wi-Fi is off.", "El Wi-Fi está apagado."},
	{"Available networks", "Redes disponibles"},
	{"Looking for networks…", "Buscando redes…"},
	{"No other networks found.", "No se encontraron otras redes."},
	{"Network settings", "Configuración de red"},
	{"Disconnect", "Desconectar"},
	{"Saved", "Guardada"},
	{"Connect", "Conectar"},
	{"Password", "Contraseña"},
	{"Clipboard", "Portapapeles"},
	{"Clear all", "Borrar todo"},
	{"Nothing copied yet", "Todavía no has copiado nada"},
	{"Text and pictures you copy", "Los textos e imágenes que copies"},
	{"show up here.", "aparecen aquí."},
	{"AREA", "ÁREA"},
	{"Apps", "Aplicaciones"},
	{"Run", "Ejecutar"},
	{"Windows", "Ventanas"},
	{"Search…", "Buscar…"},
	{"now", "ahora"},
	{"Notification", "Notificación"},
	{"unknown", "desconocido"},
	{"Another notification service is running (%s)", "Otro servicio de notificaciones está activo (%s)"},
	{"Notification service unavailable (no D-Bus)", "Servicio de notificaciones no disponible (sin D-Bus)"},
	{"Notifications", "Notificaciones"},
	{"No new notifications", "No hay notificaciones nuevas"},
	{"Do not disturb is on", "No molestar está activado"},
	{"Style", "Estilo"},
	{"Layouts", "Modelos"},
	{"Widgets", "Widgets"},
	{"Terminal", "Terminal"},
	{"Music", "Música"},
	{"START", "INICIO"},
	{"CENTER", "CENTRO"},
	{"END", "FINAL"},
	{"AVAILABLE", "DISPONIBLES"},
	{"Empty", "Vacío"},
	{"All on the bar", "Todos en la barra"},
	{"Pick a widget on the bar to move or remove it, or an available one to add it.", "Elige un widget de la barra para moverlo o quitarlo, o uno disponible para añadirlo."},
	{"Add %s to:", "Añadir %s a:"},
	{"Start", "Inicio"},
	{"Center", "Centro"},
	{"End", "Final"},
	{"Remove", "Quitar"},
	{"BAR WIDGETS", "WIDGETS DE LA BARRA"},
	{"Visual effects", "Efectos visuales"},
	{"Shadows, animations, transparency, blur and smooth corners", "Sombras, animaciones, transparencia, desenfoque y esquinas suaves"},
	{"Compositor", "Compositor"},
	{"lactase is not installed", "lactase no está instalado"},
	{"lactase running", "lactase activo"},
	{"lactase running (OpenGL)", "lactase activo (OpenGL)"},
	{"lactase running (XRender)", "lactase activo (XRender)"},
	{"Another compositor is running", "Otro compositor está activo"},
	{"Stopped", "Detenido"},
	{"lactase settings", "Configuración de lactase"},
	{"Shadows, animations, transparency, blur and per-application rules live in lactase's settings.", "Las sombras, animaciones, transparencia, desenfoque y reglas por aplicación están en la configuración de lactase."},
	{"Window corners follow the radius under Windows; with lactase they are smooth.", "Las esquinas de las ventanas siguen el radio de Ventanas; con lactase quedan suavizadas."},
	{"Install lactase with milk's installer (./install.sh) for shadows, animations and transparency.", "Instala lactase con el instalador de milk (./install.sh) para tener sombras, animaciones y transparencia."},
	{"Default", "Predeterminado"},
	{"Automatic", "Automático"},
	{"Welcome to milk", "Bienvenido a milk"},
	{"Let's make your desktop yours in five quick steps.", "Vamos a dejar tu escritorio a tu gusto en cinco pasos rápidos."},
	{"Theme", "Tema"},
	{"Light or dark", "Claro u oscuro"},
	{"Keyboard", "Teclado"},
	{"Layout and variant", "Distribución y variante"},
	{"Wallpapers", "Fondos de pantalla"},
	{"One for all or one per area", "Uno para todas o uno por área"},
	{"Bar", "Barra"},
	{"Position and style", "Posición y estilo"},
	{"Light", "Claro"},
	{"Dark", "Oscuro"},
	{"Dark variant", "Variante oscura"},
	{"Light variant", "Variante clara"},
	{"No dead keys: ´ ~ ^ do not accent the next letter", "Sin teclas muertas: ´ ~ ^ no acentúan la letra siguiente"},
	{"No dead keys: ´ ~ ^ never accent", "Sin teclas muertas: ´ ~ ^ no acentúan"},
	{"Search layouts…", "Buscar distribución…"},
	{"No layout found", "No se encontró ninguna distribución"},
	{"VARIANT", "VARIANTE"},
	{"Type here to test: symbols, accents, @, / …", "Escribe aquí para probar: ñ, acentos, @, / …"},
	{"None (bar colour)", "Ninguno (color de la barra)"},
	{"Same on all", "El mismo en todas"},
	{"One per area", "Uno por área"},
	{"Loading wallpapers…", "Cargando fondos de pantalla…"},
	{"Loading wallpapers… %d of %d", "Cargando fondos de pantalla… %d de %d"},
	{"%d pictures found", "%d imágenes encontradas"},
	{"No wallpaper", "Sin fondo de pantalla"},
	{"solid bar colour", "color sólido de la barra"},
	{"Edge to edge", "De borde a borde"},
	{"Floating top", "Arriba flotante"},
	{"Margins and rounded corners", "Márgenes y esquinas redondeadas"},
	{"Floating bottom", "Abajo flotante"},
	{"One per area · %d areas", "Uno por área · %d áreas"},
	{"None (solid bar colour)", "Ninguno (color sólido de la barra)"},
	{"%s · every area", "%s · todas las áreas"},
	{"floating", "flotante"},
	{"edge to edge", "de borde a borde"},
	{"THEME", "TEMA"},
	{"KEYBOARD", "TECLADO"},
	{"WALLPAPERS", "FONDOS DE PANTALLA"},
	{"BAR", "BARRA"},
	{"Change", "Cambiar"},
	{"milk settings", "Configuración de milk"},
	{"Appearance", "Apariencia"},
	{"Colour theme and animation speed.", "Tema de colores y velocidad de las animaciones."},
	{"One image for every area or one per area.", "Una imagen para todas las áreas o una para cada área."},
	{"Position, style, size, widgets and date/time formats.", "Posición, estilo, tamaño, widgets y formatos de fecha y hora."},
	{"Effects", "Efectos"},
	{"Shadows, animations and transparency with lactase, milk's compositor.", "Sombras, animaciones y transparencia con lactase, el compositor de milk."},
	{"Gaps, borders and animations. Border colours follow the theme.", "Espaciado, bordes y animaciones. Los colores de los bordes siguen el tema."},
	{"Shortcuts", "Atajos"},
	{"Key combinations that open applications, commands and sites.", "Combinaciones de teclas que abren aplicaciones, comandos y sitios."},
	{"Language and keyboard", "Idioma y teclado"},
	{"milk's language and the keyboard layout and variant, applied at once.", "Idioma de milk y distribución y variante del teclado, aplicados al instante."},
	{"Pop-ups shown in a corner of the screen.", "Avisos que aparecen en una esquina de la pantalla."},
	{"History of copied text and images.", "Historial de textos e imágenes copiados."},
	{"Areas", "Áreas"},
	{"Workspace names, shown by the area toast.", "Nombres de las áreas de trabajo, mostrados en el aviso de área."},
	{"About", "Acerca de"},
	{"Version, files and the setup wizard.", "Versión, archivos y asistente inicial."},
	{"Animation speed", "Velocidad de las animaciones"},
	{"Windows, bar, panels and toasts", "Ventanas, barra, paneles y avisos"},
	{"Slow", "Lentas"},
	{"Language", "Idioma"},
	{"Menus, panels, dates and this app", "Menús, paneles, fechas y esta aplicación"},
	{"Settings", "Configuración"},
	{"Height", "Altura"},
	{"Opacity", "Opacidad"},
	{"Margin (floating)", "Margen (flotante)"},
	{"Corners (floating)", "Esquinas (flotante)"},
	{"Date", "Fecha"},
	{"Clock", "Reloj"},
	{"Between windows and the screen edges", "Entre las ventanas y los bordes de la pantalla"},
	{"Focused window: the theme accent", "Ventana enfocada: el color de acento del tema"},
	{"Rounded corners", "Esquinas redondeadas"},
	{"Radius of the window corners", "Radio de las esquinas de las ventanas"},
	{"Master area", "Área principal"},
	{"Width of the main window", "Ancho de la ventana principal"},
	{"Focus follows mouse", "El foco sigue al ratón"},
	{"Focus the window under the pointer", "Enfocar la ventana bajo el puntero"},
	{"Window animation", "Animación de las ventanas"},
	{"Duration when opening, moving and resizing", "Duración al abrir, mover y redimensionar"},
	{"Receive pop-ups from applications", "Recibir avisos de las aplicaciones"},
	{"Do not disturb", "No molestar"},
	{"Keep them in the history without showing them", "Guardarlos en el historial sin mostrarlos"},
	{"Time on screen", "Tiempo en pantalla"},
	{"When the application does not say", "Cuando la aplicación no lo indica"},
	{"Position", "Posición"},
	{"Top right", "Arriba a la derecha"},
	{"Bottom right", "Abajo a la derecha"},
	{"History", "Historial"},
	{"Keep what is copied", "Guardar lo que se copie"},
	{"Items kept", "Elementos guardados"},
	{"Keep after restarting", "Conservar al reiniciar"},
	{"Save the history in milk's folder", "Guardar el historial en la carpeta de milk"},
	{"Area %d", "Área %d"},
	{"No name (AREA %d)", "Sin nombre (ÁREA %d)"},
	{"Version %s", "Versión %s"},
	{"CONFIGURATION", "CONFIGURACIÓN"},
	{"DATA", "DATOS"},
	{"Run the setup wizard again", "Volver a ejecutar el asistente inicial"},
	{"Open milk.json", "Abrir milk.json"},
	{"The wizard appears the next time milk starts.", "El asistente aparecerá la próxima vez que se inicie milk."},
	{"The wizard will open next time", "El asistente se abrirá la próxima vez"},
	{"Could not save", "No se pudo guardar"},
	{"Saved and applied", "Guardado y aplicado"},
	{"Space", "Espacio"},
	{"Mute", "Silencio"},
	{"Brightness +", "Brillo +"},
	{"Brightness −", "Brillo −"},
	{"Next", "Siguiente"},
	{"Previous", "Anterior"},
	{"Hold a modifier (Super, Ctrl, Alt or Shift) with the key.", "Usa una tecla modificadora (Super, Ctrl, Alt o Shift) junto con la tecla."},
	{"Your shortcuts", "Tus atajos"},
	{"Add shortcut", "Añadir atajo"},
	{"No shortcuts yet: add one to open your favourite apps and sites.", "Todavía no hay atajos: crea uno para abrir tus aplicaciones y sitios favoritos."},
	{"milk's shortcuts", "Atajos de milk"},
	{"A shortcut of yours with the same keys replaces milk's", "Un atajo tuyo con las mismas teclas sustituye al de milk"},
	{"New shortcut", "Nuevo atajo"},
	{"Edit shortcut", "Editar atajo"},
	{"KEY COMBINATION", "COMBINACIÓN DE TECLAS"},
	{"Press the combination…  (Esc cancels)", "Pulsa la combinación…  (Esc cancela)"},
	{"Click to change", "Haz clic para cambiar"},
	{"Click here and press the key combination", "Haz clic aquí y pulsa la combinación de teclas"},
	{"Already one of your shortcuts: it is replaced when you save.", "Ya es uno de tus atajos: se sustituirá al guardar."},
	{"Replaces: %s (milk shortcut)", "Sustituye: %s (atajo de milk)"},
	{"OPEN", "ABRIR"},
	{"Application", "Aplicación"},
	{"Command", "Comando"},
	{"Site or folder", "Sitio o carpeta"},
	{"Search applications…", "Buscar aplicación…"},
	{"E.g. alacritty -e htop", "Ej.: alacritty -e htop"},
	{"Run with /bin/sh -c, like milk's other shortcuts.", "Se ejecuta con /bin/sh -c, como los demás atajos de milk."},
	{"E.g. https://example.com or ~/Documents", "Ej.: https://example.com o ~/Documentos"},
	{"Opened with xdg-open in the default application.", "Se abre con xdg-open en la aplicación predeterminada."},
	{"Save", "Guardar"},
	{"Cancel", "Cancelar"},
	{"No application found", "No se encontró ninguna aplicación"},
	{"Bar background", "Fondo de la barra"},
	{"Surface", "Superficie"},
	{"Foreground", "Texto"},
	{"Muted", "Texto suave"},
	{"Accent", "Acento"},
	{"Accent foreground", "Texto sobre el acento"},
	{"Warning", "Alerta"},
	{"Window border", "Borde de las ventanas"},
	{"Focused window", "Ventana enfocada"},
	{"YOUR THEMES", "TUS TEMAS"},
	{"New theme", "Nuevo tema"},
	{"Make a theme with your own colours: it applies to the bar, windows, panels and terminal.", "Crea un tema con tus colores: se aplica a la barra, las ventanas, los paneles y la terminal."},
	{"My theme", "Mi tema"},
	{"Give the theme a name.", "Ponle un nombre al tema."},
	{"That is the name of a milk theme.", "Ese nombre es de un tema de milk."},
	{"There is already a theme with that name.", "Ya existe un tema con ese nombre."},
	{"Edit theme", "Editar tema"},
	{"Theme name", "Nombre del tema"},
	{"Hue", "Tono"},
	{"Saturation", "Saturación"},
	{"Lightness", "Luminosidad"},
	{"Save and use", "Guardar y usar"},
	{"Confirm delete", "Confirmar eliminación"},
	{"Delete", "Eliminar"},
	{"Skip setup", "Omitir configuración"},
	{"Let's go", "Empezar"},
	{"Back", "Atrás"},
	{"Choose your theme", "Elige tu tema"},
	{"Colours for the bar, the panels, window borders and the terminal.", "Colores de la barra, los paneles, los bordes de las ventanas y la terminal."},
	{"Pick your keyboard layout and variant, then try it in the test field.", "Elige la distribución y la variante de tu teclado y pruébalas escribiendo en el campo de prueba."},
	{"One image for every workspace, or a different one for each area.", "Una imagen para todas las áreas de trabajo, o una distinta para cada área."},
	{"Where the bar sits and how it meets the screen edges.", "Dónde va la barra y cómo se apoya en la pantalla."},
	{"All set", "Todo listo"},
	{"Review your choices. Everything can be changed later in the bar's quick settings or in milk.json.", "Revisa tus elecciones. Todo se puede cambiar después en los ajustes rápidos de la barra o en milk.json."},
	{"Launcher", "Lanzador"},
	{"Active window", "Ventana activa"},
	{"Workspaces", "Áreas"},
	{"Open windows", "Ventanas abiertas"},
	{"Window", "Ventana"},
	{"Media", "Multimedia"},
	{"Network", "Red"},
	{"Bluetooth", "Bluetooth"},
	{"Volume", "Volumen"},
	{"Brightness", "Brillo"},
	{"Battery", "Batería"},
	{"Session", "Sesión"},
	{"Spacer", "Espacio"},
	{"milk", "milk"},
	{"The default: title left, areas centred", "El predeterminado: título a la izquierda, áreas en el centro"},
	{"Minimal", "Mínimo"},
	{"Just areas, the clock and the essentials", "Solo áreas, reloj y lo esencial"},
	{"Classic", "Clásico"},
	{"Windows-like: bottom, clock in the corner", "Como en Windows: abajo, con el reloj en la esquina"},
	{"Centred", "Centrado"},
	{"Floating at the bottom, essentials in the middle", "Flotante abajo, con lo esencial en el centro"},
	{"macOS", "macOS"},
	{"At the top, clock and settings on the right", "Arriba, con reloj y ajustes a la derecha"},
	{"Open the terminal", "Abrir la terminal"},
	{"Open the application launcher", "Abrir el lanzador de aplicaciones"},
	{"Close the window", "Cerrar la ventana"},
	{"Focus the next / previous window", "Enfocar la ventana siguiente / anterior"},
	{"Swap with the master window", "Intercambiar con la ventana principal"},
	{"Shrink / grow the master area", "Reducir / ampliar el área principal"},
	{"More / fewer windows in the master area", "Más / menos ventanas en el área principal"},
	{"Tile / floating / monocle layout", "Mosaico / flotante / monóculo"},
	{"Previous layout", "Disposición anterior"},
	{"Toggle floating", "Alternar ventana flotante"},
	{"Fullscreen", "Pantalla completa"},
	{"Go to area 1…9", "Ir al área 1…9"},
	{"Move the window to area 1…9", "Mover la ventana al área 1…9"},
	{"Also show area 1…9", "Mostrar también el área 1…9"},
	{"Also put the window on area 1…9", "Poner la ventana también en el área 1…9"},
	{"All areas / window on all areas", "Todas las áreas / ventana en todas"},
	{"Previous area", "Área anterior"},
	{"Focus the previous / next monitor", "Enfocar el monitor anterior / siguiente"},
	{"Move the window to another monitor", "Mover la ventana a otro monitor"},
	{"Clipboard history", "Historial del portapapeles"},
	{"Notification panel", "Panel de notificaciones"},
	{"Screenshot of a region", "Captura de una región de la pantalla"},
	{"Reload milk.json", "Recargar milk.json"},
	{"Quit milk", "Salir de milk"},
	{"Mute / volume − / volume +", "Silencio / volumen − / volumen +"},
	{"Brightness − / +", "Brillo − / +"},
	// Floating mode, window menus, desktop icons settings.
	{"Files", "Archivos"},
	{"Applications…", "Aplicaciones…"},
	{"New folder", "Nueva carpeta"},
	{"Arrange icons", "Ordenar los iconos"},
	{"Open the Desktop folder", "Abrir la carpeta del escritorio"},
	{"Wallpaper…", "Fondo de pantalla…"},
	{"Reload", "Recargar"},
	{"Log out", "Cerrar sesión"},
	{"No windows", "No hay ventanas"},
	{"Minimize", "Minimizar"},
	{"Restore", "Restaurar"},
	{"Maximize", "Maximizar"},
	{"Shade", "Enrollar"},
	{"Always on top", "Siempre encima"},
	{"Always below", "Siempre debajo"},
	{"On every area", "En todas las áreas"},
	{"Title bar", "Barra de título"},
	{"Left half", "Mitad izquierda"},
	{"Right half", "Mitad derecha"},
	{"Centre", "Centrar"},
	{"Move to area", "Mover al área"},
	{"Move to the other monitor", "Mover al otro monitor"},
	{"Close", "Cerrar"},
	{"minimized", "minimizada"},
	{"Mode", "Modo"},
	{"Windows with title bars that you move and overlap", "Ventanas con barra de título que mueves y superpones"},
	{"Windows share the screen between them", "Las ventanas se reparten la pantalla"},
	{"Tiling", "En mosaico"},
	{"General", "General"},
	{"Behaviour", "Comportamiento"},
	{"Margin", "Margen"},
	{"Around maximized and snapped windows", "Alrededor de las ventanas maximizadas y ajustadas"},
	{"Buttons", "Botones"},
	{"Icons", "Iconos"},
	{"Circles", "Círculos"},
	{"Button side", "Lado de los botones"},
	{"Right", "Derecha"},
	{"Left", "Izquierda"},
	{"Title", "Título"},
	{"Document — Editor", "Documento — Editor"},
	{"New windows", "Ventanas nuevas"},
	{"Where windows appear", "Dónde aparecen las ventanas"},
	{"Free space", "Espacio libre"},
	{"Pointer", "Puntero"},
	{"Cascade", "Cascada"},
	{"Snap to edges", "Ajustar a los bordes"},
	{"Drag to an edge: half, quarter or maximized", "Arrastra a un borde: mitad, cuarto o maximizada"},
	{"Resistance", "Resistencia"},
	{"Windows stick to the edges and to each other", "Las ventanas se pegan a los bordes y entre sí"},
	{"Raise on focus", "Traer al frente al enfocar"},
	{"With focus following the mouse", "Con el foco siguiendo al ratón"},
	{"Files on the desktop", "Archivos en el escritorio"},
	{"What the Desktop folder holds, as icons", "Lo que contiene la carpeta Escritorio, como iconos"},
	{"Area shortcuts", "Atajos de las áreas"},
	{"The shortcuts of each area", "Los atajos de cada área"},
	{"In the folder", "En la carpeta"},
	{"Hidden", "Ocultos"},
	{"Icon size", "Tamaño de los iconos"},
	{"Open with one click", "Abrir con un clic"},
	{"Image thumbnails", "Miniaturas de imágenes"},
	{"Hidden files", "Archivos ocultos"},
	{"Arrange by", "Ordenar por"},
	{"For icons without a place yet", "Para los iconos que aún no tienen lugar"},
	{"Name", "Nombre"},
	{"Type", "Tipo"},
	{"Windows share the screen without overlapping", "Las ventanas se reparten la pantalla sin superponerse"},
	{"Title bars, dragging, maximizing and snapping", "Barras de título, arrastrar, maximizar y ajustar"},
	{"Show the Desktop folder as icons over the wallpaper", "Mostrar la carpeta Escritorio como iconos sobre el fondo"},
	{"Side by side like dwm, or floating with title bars like openbox and Windows.", "Lado a lado como en dwm, o flotantes con barra de título como en openbox y Windows."},
	{"Tiling or floating", "En mosaico o flotantes"},
	{"WINDOWS", "VENTANAS"},
	{"files on the desktop", "archivos en el escritorio"},
	{"Tiling or floating, borders, title bars and animations.", "En mosaico o flotantes, bordes, barras de título y animaciones."},
	{"Desktop", "Escritorio"},
	{"File and shortcut icons over the wallpaper.", "Iconos de archivos y atajos sobre el fondo de pantalla."},
	{"Switch between windows", "Cambiar entre ventanas"},
	{"Maximize / restore", "Maximizar / restaurar"},
	{"Restore or minimize", "Restaurar o minimizar"},
	{"Snap to the left / right half", "Ajustar a la mitad izquierda / derecha"},
	{"Centre the window", "Centrar la ventana"},
	{"Show the desktop", "Mostrar el escritorio"},
	{"Window menu", "Menú de la ventana"},
	{"Previous / next area", "Área anterior / siguiente"},
	{"Take the window to the previous / next area", "Llevar la ventana al área anterior / siguiente"},
	{"Window action", "Acción de la ventana"},
	{"WHAT IT DOES", "QUÉ HACE"},
	{"Key combinations for applications, commands, sites and window actions.", "Combinaciones de teclas para aplicaciones, comandos, sitios y acciones de las ventanas."},
	{"Snap to the left half", "Ajustar a la mitad izquierda"},
	{"Snap to the right half", "Ajustar a la mitad derecha"},
	{"Snap to the top-left quarter", "Ajustar al cuarto superior izquierdo"},
	{"Snap to the top-right quarter", "Ajustar al cuarto superior derecho"},
	{"Snap to the bottom-left quarter", "Ajustar al cuarto inferior izquierdo"},
	{"Snap to the bottom-right quarter", "Ajustar al cuarto inferior derecho"},
	{"Show / hide the title bar", "Mostrar / ocultar la barra de título"},
	{"Send to the back", "Enviar al fondo"},
	{"Desktop menu", "Menú del escritorio"},
	{"Window list", "Lista de ventanas"},
	{"Next area", "Área siguiente"},
	{"Take the window to the next area", "Llevar la ventana al área siguiente"},
	{"Take the window to the previous area", "Llevar la ventana al área anterior"},
	{"Open", "Abrir"},
	{"Open in terminal", "Abrir en la terminal"},
	{"Copy path", "Copiar ruta"},
	{"Copy paths", "Copiar rutas"},
	{"Rename…", "Cambiar nombre…"},
	{"Move to Trash", "Mover a la papelera"},
}
